.TH dnet-CONFIG 1 "23 Aug 2009"
.SH NAME
dnet-config \- provide compiler and linker information for libdnet
.SH SYNOPSIS
.BR dnet-config " [ " \-\-version " | " \-\-cflags " | " \-\-libs " ]"
.SH DESCRIPTION
.I dnet-config
prints the library version (\fB\-\-version\fR) or the necessary compiler
(\fB\-\-cflags\fR) or linker flags (\fB\-\-libs\fR) to build software
based on this library.
.SH SEE ALSO
.BR dnet "(3), " dnet (8)
