.TH DUMBNET-CONFIG 1 "23 Aug 2009"
.SH NAME
dumbnet-config \- provide compiler and linker information for libdumbnet
.SH SYNOPSIS
.BR dumbnet-config " [ " \-\-version " | " \-\-cflags " | " \-\-libs " ]"
.SH DESCRIPTION
.I dumbnet-config
prints the library version (\fB\-\-version\fR) or the necessary compiler
(\fB\-\-cflags\fR) or linker flags (\fB\-\-libs\fR) to build software
based on this library.
.SH SEE ALSO
.BR dumbnet "(3), " dumbnet (8)
